# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cardProcessor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/cardProcessor.proto\x12\rcardProcessor\"\xc1\x01\n\x12TransactionRequest\x12\x10\n\x08pinBlock\x18\x01 \x01(\t\x12P\n\x12transactionDetails\x18\x02 \x01(\x0b\x32\x34.cardProcessor.TransactionRequest.TransactionDetails\x1aG\n\x12TransactionDetails\x12\x0e\n\x06vendor\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"&\n\x13TransactionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x13TokenisationRequest\x12\x10\n\x08pinBlock\x18\x01 \x01(\t\"1\n\x14TokenisationResponse\x12\x19\n\x11tokenisedPinBlock\x18\x01 \x01(\t2\x13\n\x11MasterCardService2t\n\x13TokenisationService\x12]\n\x10TokenisePinBlock\x12\".cardProcessor.TokenisationRequest\x1a#.cardProcessor.TokenisationResponse\"\x00\x32\x18\n\x16\x43ryptoValidatorService2\x0c\n\nHSMServiceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cardProcessor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSACTIONREQUEST._serialized_start=45
  _TRANSACTIONREQUEST._serialized_end=238
  _TRANSACTIONREQUEST_TRANSACTIONDETAILS._serialized_start=167
  _TRANSACTIONREQUEST_TRANSACTIONDETAILS._serialized_end=238
  _TRANSACTIONRESPONSE._serialized_start=240
  _TRANSACTIONRESPONSE._serialized_end=278
  _TOKENISATIONREQUEST._serialized_start=280
  _TOKENISATIONREQUEST._serialized_end=319
  _TOKENISATIONRESPONSE._serialized_start=321
  _TOKENISATIONRESPONSE._serialized_end=370
  _MASTERCARDSERVICE._serialized_start=372
  _MASTERCARDSERVICE._serialized_end=391
  _TOKENISATIONSERVICE._serialized_start=393
  _TOKENISATIONSERVICE._serialized_end=509
  _CRYPTOVALIDATORSERVICE._serialized_start=511
  _CRYPTOVALIDATORSERVICE._serialized_end=535
  _HSMSERVICE._serialized_start=537
  _HSMSERVICE._serialized_end=549
# @@protoc_insertion_point(module_scope)
