---
version: "3.8"

services:

  mastercard-service:
    build: ./mastercard-service
    ports:
      - 8000:8000
    environment:
      PORT: 8000

  tokenisation-service:
    build: ./tokenisation-service
    ports:
      - 50051:50051
    environment:
      PORT: 50051
