# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import cardProcessor_pb2 as proto_dot_cardProcessor__pb2


class MasterCardServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """


class MasterCardServiceServicer(object):
    """Missing associated documentation comment in .proto file."""


def add_MasterCardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cardProcessor.MasterCardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MasterCardService(object):
    """Missing associated documentation comment in .proto file."""


class TokenisationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TokenisePinBlock = channel.unary_unary(
                '/cardProcessor.TokenisationService/TokenisePinBlock',
                request_serializer=proto_dot_cardProcessor__pb2.TokenisationRequest.SerializeToString,
                response_deserializer=proto_dot_cardProcessor__pb2.TokenisationResponse.FromString,
                )


class TokenisationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TokenisePinBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TokenisationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TokenisePinBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.TokenisePinBlock,
                    request_deserializer=proto_dot_cardProcessor__pb2.TokenisationRequest.FromString,
                    response_serializer=proto_dot_cardProcessor__pb2.TokenisationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cardProcessor.TokenisationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TokenisationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TokenisePinBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cardProcessor.TokenisationService/TokenisePinBlock',
            proto_dot_cardProcessor__pb2.TokenisationRequest.SerializeToString,
            proto_dot_cardProcessor__pb2.TokenisationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class CryptoValidatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """


class CryptoValidatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""


def add_CryptoValidatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cardProcessor.CryptoValidatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CryptoValidatorService(object):
    """Missing associated documentation comment in .proto file."""


class HSMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """


class HSMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""


def add_HSMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cardProcessor.HSMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HSMService(object):
    """Missing associated documentation comment in .proto file."""
